### PR TITLE
Change swipes list icon to font awesome

### PR DESCRIPTION
**Pull request by Wolfsblvt**
Changed the icon for the "view swipes" on the three-dots right menu to a font awesome icon that matches the style and size of all the others.

image

If you don't think that icon matches the spirit of the intention, there are other fa icons we could choose. I thought the arrows work though, as swipes are usually represented by arrows.  
Any of those I could see to work too:
image

### CODE REVIEW

**Comment by Cohee1207** [comment]
`layer-group` I like

**Comment by Wolfsblvt** [comment]
For this one? I can change it. Was a close decision between the two for me.

**Comment by Cohee1207** [comment]
Arrows don't convey an appropriate visual message for me.

**Review by Cohee1207 — APPROVED** [review]
LGTM

**Pull request merged**
